### ISSUE TITLE
Create hierarchical deterministic key derivation library

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-base#151]
**Task description**
Add a library for generating keys according to the newly defined Concordium key derivation scheme. The key derivation scheme is defined in the cryptographic bluepaper. The key derivation scheme is based on [SLIP0010](https://github.com/satoshilabs/slips/blob/master/slip-0010.md), and this library will contain an implementation of that standard for the ed25519 curve.

The library will expose the methods required by clients (e.g. mobile wallets, desktop wallet, browser wallet) for getting identity and account keys, and randomness, given their respective indices as input. Clients will only have to provide a seed phrase and an identity index, or an identity index and account index pair to get the key and randomness material required.

This task is also responsible for making sure that the library is exposed for use in the mobile wallets.

**Comment by abizjak** [comment]
Closed by #157
