### ISSUE TITLE
Productivization of the trace_account tool

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-base#26]
**Task description**

Trace-account should be expanded to support all transaction types and be more robust wrt failure.
Possibly it should be expanded to support more source types.

**Sub-tasks**
- [ ] support output in CSV format
- [ ] #77
- [ ] support querying accounts via credid to get all accounts and not just the ones created by the owner of the credential.

**Comment by simonkamp** [comment]
Tool moved to use-case-examples
