### ISSUE TITLE
Check for duplicated idCredPub

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-base#304]
**Description**
It seems that if trying to use the same IdCredPub, Identity Provider just overwrites the Identity that already exists.
We should check for the duplicate and return an error.

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by abizjak** [comment]
This was closed by #305
