### ISSUE TITLE
New Consensus: M1 Fix TimeoutParameters.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-base#327]
First problem currently is, that we do not check whether the denominator is zero when deserializing the `TimeoutParameters` structure.

This should be fixed and an appropriate error should be returned if it is the case.

Secondly we should probably not use `Ratio` for these values because `Ratio` does not play along well with silent overflows. 

e.g. 

```
ghci> (251 % 252 :: Ratio Word8) >= 2 % 3
False
```

So let's introduce our own type for these and expose the few capabilities we need.

**Comment by abizjak** [comment]
What do you mean it does not play along with multiplication? How does the example you have demonstrate that?

**Comment by EmilLa1** [comment]
Yea sorry for vague description, but it's due to silent overflow e.g.

```
(251 % 253 :: Ratio Word8) >= 2 % 3  <=/>   251 * 3    >= 2 * 252  =>  241 >= 248
;```

**Comment by EmilLa1** [comment]
More context: https://gitlab.haskell.org/ghc/ghc/-/issues/19500

**Comment by abizjak** [comment]
Very nice. :P 

The comment
```
(251 % 253 :: Ratio Word8) > 2 % 3
```
was confusing since, well, that relation is correct :P

**Comment by abizjak** [comment]
Is this still relevant or was it fixed?

**Comment by EmilLa1** [comment]
Yes. 

I have posted this PR which addresses the missing denominator checks. 

However, I have not introduced a new type *yet* to use instead of the `Ratio` as I don't think it matters when we normalise parameters.

If you think it's worth to add a new type, then I'll do it.

**Comment by EmilLa1** [comment]
Closing this now as https://github.com/Concordium/concordium-base/pull/390 is merged into main. 

We should however be careful in the future if we start to compare the growth and shrink factors after the deserialization.
