### ISSUE TITLE
User_cli tool throws an error if using --account flag

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-base#339]
**Bug Description**
Creating credentials for an account to be updated with new credentials is limited with the issue that when --account flag is used, the tool returns an error.

Try to `create-credential-v1` and use `--account` flag. 
To be able to try this, you need to issue identity using user_cli and identity-provider-cli tools.

**Steps to Reproduce**
1.  Follow this [guide](https://github.com/Concordium/concordium-base/blob/main/rust-bins/docs/user-cli.md), first, doing the generate request part of the process (V1 flow).
2. Follow this [guide ](https://github.com/Concordium/concordium-base/blob/main/rust-bins/docs/identity-provider-cli.md)as Identity provider.
3. Then try the credential flow in the [guide ](https://github.com/Concordium/concordium-base/blob/main/rust-bins/docs/user-cli.md#create-accounts-from-a-version-1-identity-object)but use `--account` flag to create credentials that will be update to already existing account.

Example of my request
`.\user_cli.exe create-credential-v1 --cryptographic-parameters .\cryptographic-parameters-testnet.json --ars .\ars-testnet.json --ip-info .\ip-info-testnet.json --account 48eN2g4DrFqUmRnxWNXGnL4LrvKxBF4Urw2cvLPM7v3K8TrscW --id-object .\identity\id-object.json --keys-out .\identity\account1\account-keys.json --credential-out .\identity\account1\credential.json`

**Expected Result**
No errors.

**Actual Result**
```
error: The argument '--account <account>' cannot be used with '--message-expiry <expiry>'

USAGE:
    user_cli.exe create-credential-v1 --account <account> --ars <anonymity-revokers> --cryptographic-parameters <cryptographic-parameters> --message-expiry <expiry> --id-object <id-object> --ip-info <ip-info> --key-index <key-index> --keys-out <keys-out> --credential-out <out>
```

**Versions**
- Software Version: User CLI 2.1.0

**Comment by rasmus-kirk** [comment]
Closed with #420
