### ISSUE TITLE
What is called witness in sigma protocols is not what is typically called a witness

### ISSUE THREAD

**Issue by chrmatt** [Concordium/concordium-base#408]
In the current implementation of sigma protocols, a proof contains an element called "witness", which corresponds to the last message sent in an interactive version of the sigma protocol. This keeps confusing people because in cryptography, a witness is a secret value known to the prover that proves correctness of the claimed statement, and the magic of ZK is to prove that statement without revealing the witness. So having the witness as part of the proof seems very wrong, until you realize that this is not actually the witness.

We should ideally change the terminology to make it more consistent with the literature.

**Comment by abizjak** [comment]
Resolved by #422
