### ISSUE TITLE
Use different g's in commitment keys for Web3ID attributes

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-base#412]
**Task description**
Revise the commitment keys to have different `g`s so that a commitment key `(g_i, h)` will be used for a commitment to a value for attribute tag `i`.

**Comment by abizjak** [comment]
Since this has unclear utility and quite a bit of complexity we are not going to do it, as discussed on Wednesday with @eb-concordium and @hamiidreza .
